// examples/Svelte/datepicker/src/routes/datepicker.svelte
<script lang="ts">
  import { useCalendar } from '@verbpatch/svelte-calendar';

  interface Props {
    label: string;
    value?: Date;
    placeholder?: string;
  }

  let { label, value = $bindable(), placeholder = 'Select a date' }: Props = $props();

  let isOpen = $state(false);
  let containerRef: HTMLDivElement;

  const calendar = useCalendar({
    calendarId: `datepicker-${label.replace(/\s+/g, '-').toLowerCase()}`,
    defaultView: 'month',
    defaultDate: value || new Date(),
  });

  function handleClickOutside(event: MouseEvent) {
    if (containerRef && !containerRef.contains(event.target as Node)) {
      isOpen = false;
    }
  }

  $effect(() => {
    document.addEventListener('mousedown', handleClickOutside);
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  });

  function handleDateSelect(date: Date) {
    value = date;
    isOpen = false;
  }

  const displayValue = $derived(value ? $calendar.utils.formatDate(value, 'yyyy-MM-dd') : '');
</script>

<div bind:this={containerRef} style="position: relative; margin-bottom: 20px">
  <label style="display: block">{label}</label>
  <input
    type="text"
    readonly
    value={displayValue}
    {placeholder}
    onclick={() => (isOpen = !isOpen)}
  />

  {#if isOpen}
    <div style="position: absolute; top: 100%; left: 0; z-index: 1000; background: white; border: 1px solid black; padding: 10px">
      <div style="display: flex; justify-content: space-between">
        <button type="button" onclick={(e) => { e.stopPropagation(); $calendar.goToPrevious(); }}>←</button>
        <span>{$calendar.utils.formatLocalizedMonth($calendar.currentDate)}</span>
        <button type="button" onclick={(e) => { e.stopPropagation(); $calendar.goToNext(); }}>→</button>
      </div>

      <table>
        <thead>
          <tr>
            {#each $calendar.utils.daysofWeek('narrow') as day, index (day + '-' + index)}
              <th>{day}</th>
            {/each}
          </tr>
        </thead>
        <tbody>
          {#if $calendar.monthData?.weeks}
            {#each $calendar.monthData.weeks as week, i}
              <tr>
                {#each week as date, j}
                  {@const isCurrentMonth = $calendar.monthData?.isCurrentMonth(date)}
                  {@const isSelected = value && date.toDateString() === value.toDateString()}
                  {@const isToday = $calendar.monthData?.isToday(date)}
                  <td
                    onclick={(e) => { e.stopPropagation(); isCurrentMonth && handleDateSelect(date); }}
                    style="
                      cursor: {isCurrentMonth ? 'pointer' : 'default'};
                      color: {isCurrentMonth ? (isSelected ? 'blue' : 'black') : 'gray'};
                      font-weight: {isToday ? 'bold' : 'normal'};
                      border: {isSelected ? '1px solid blue' : 'none'};
                      text-align: center;
                      padding: 4px;
                    "
                  >
                    {date.getDate()}
                  </td>
                {/each}
              </tr>
            {/each}
          {/if}
        </tbody>
      </table>

      <div style="text-align: center; margin-top: 5px">
        <button type="button" onclick={(e) => { e.stopPropagation(); handleDateSelect(new Date()); }}>Today</button>
      </div>
    </div>
  {/if}
</div>

// examples/Vuejs/datepicker/src/DatePicker.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import { useCalendar } from '@verbpatch/vuejs-calendar';

const props = defineProps<{
  label: string;
  modelValue?: Date;
  placeholder?: string;
}>();

const emit = defineEmits(['update:modelValue']);

const isOpen = ref(false);
const containerRef = ref<HTMLElement | null>(null);

const calendar = useCalendar({
  calendarId: `datepicker-${props.label.replace(/\s+/g, '-').toLowerCase()}`,
  defaultView: 'month',
  defaultDate: props.modelValue || new Date(),
});

const handleClickOutside = (event: MouseEvent) => {
  if (containerRef.value && !containerRef.value.contains(event.target as Node)) {
    isOpen.value = false;
  }
};

onMounted(() => {
  document.addEventListener('mousedown', handleClickOutside);
});

onUnmounted(() => {
  document.removeEventListener('mousedown', handleClickOutside);
});

const handleDateSelect = (date: Date) => {
  emit('update:modelValue', date);
  isOpen.value = false;
};

const formatDateValue = (date?: Date) => {
  if (!date) return '';
  return calendar.value?.utils.formatDate(date, 'yyyy-MM-dd') || '';
};
</script>

<template>
  <div ref="containerRef" style="position: relative; margin-bottom: 20px">
    <label style="display: block">{{ label }}</label>
    <input
      type="text"
      readOnly
      :value="formatDateValue(modelValue)"
      :placeholder="placeholder || 'Select a date'"
      @click="isOpen = !isOpen"
    />

    <div
      v-if="isOpen"
      style="
        position: absolute;
        top: 100%;
        left: 0;
        z-index: 1000;
        background: white;
        border: 1px solid black;
      "
    >
      <div style="display: flex; justify-content: space-between">
        <button type="button" @click.stop="calendar?.goToPrevious">←</button>
        <span>{{ calendar?.utils.formatLocalizedMonth(calendar.currentDate) }}</span>
        <button type="button" @click.stop="calendar?.goToNext">→</button>
      </div>

      <table>
        <thead>
          <tr>
            <th v-for="(day, index) in calendar?.utils.daysofWeek('narrow')" :key="index">
              {{ day }}
            </th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="(week, i) in calendar?.monthData?.weeks" :key="i">
            <td
              v-for="(date, j) in week"
              :key="j"
              @click.stop="calendar?.monthData?.isCurrentMonth(date) && handleDateSelect(date)"
              :style="{
                cursor: calendar?.monthData?.isCurrentMonth(date) ? 'pointer' : 'default',
                color: calendar?.monthData?.isCurrentMonth(date)
                  ? modelValue && date.toDateString() === modelValue.toDateString()
                    ? 'blue'
                    : 'black'
                  : 'gray',
                fontWeight: calendar?.monthData?.isToday(date) ? 'bold' : 'normal',
                border:
                  modelValue && date.toDateString() === modelValue.toDateString()
                    ? '1px solid blue'
                    : 'none',
              }"
            >
              {{ date.getDate() }}
            </td>
          </tr>
        </tbody>
      </table>

      <div style="text-align: center">
        <button type="button" @click.stop="handleDateSelect(new Date())">Today</button>
      </div>
    </div>
  </div>
</template>
