// packages/qwik-calendar/src/index.ts
import { useStore } from '@builder.io/qwik';
import { useCalendar as createCalendar, CalendarOptions } from '@verbpatch/headless-calendar';
export * from '@verbpatch/headless-calendar';

export function useCalendar(options: CalendarOptions) {
    const state = useStore({ changed: 0 });
    const calendar = createCalendar({
        ...options,
        onEvent: (event) => {
            state.changed++;
            options?.onEvent?.(event);
        },
        onDateChange: (date) => {
            state.changed++;
            options?.onDateChange?.(date);
        },
        onViewChange: (view) => {
            state.changed++;
            options?.onViewChange?.(view);
        },
    });

    return calendar;
}

// packages/react-calendar/src/index.tsx
import { useState } from "react";
export * from "@verbpatch/headless-calendar";

import {
  useCalendar as createCalendar,
  CalendarOptions,
} from "@verbpatch/headless-calendar";

export default function useCalendar(options: CalendarOptions) {
  const [stateChanged, setStateChanged] = useState(0);
  const calendar = createCalendar({
    ...options,
    onEvent: (event) => {
      setStateChanged((stateChanged) => stateChanged + 1);
      options.onEvent?.(event);
    },
    onDateChange: (date) => {
      setStateChanged((stateChanged) => stateChanged + 1);
      options.onDateChange?.(date);
    },
    onViewChange: (view) => {
      setStateChanged((stateChanged) => stateChanged + 1);
      options.onViewChange?.(view);
    },
  });

  return calendar;
}
