// examples/Vuejs/minimal/src/calendar.vue
<script setup lang="ts">
import { useCalendar } from '@verbpatch/vuejs-calendar';

const calendar = useCalendar({
  defaultView: 'month',
  startOfWeek: 0,
  locale: 'en-IN',
});
</script>

<template>
  <div v-if="calendar">
    <h1>Vue.js Calendar minimal Example</h1>
    <table border="0" width="840" cellspacing="0" style="height: 700px; border-left: 1px solid; border-top: 1px solid">
      <thead>
        <tr>
          <th colspan="2" style="border-bottom: 1px solid">
            <button type="button" @click="calendar.goToPrevious">←</button>
            <button type="button" @click="calendar.goToToday">Today</button>
            <button type="button" @click="calendar.goToNext">→</button>
          </th>
          <th colspan="3" style="border-bottom: 1px solid">
            <h3>
              {{ calendar.view === 'month' ? calendar.monthData?.monthName : '' }}
              {{ calendar.view === 'week' ? calendar.weekData?.weekRange : '' }}
              {{ calendar.view === 'day' ? calendar.dayData?.dayName : '' }}
            </h3>
          </th>
          <th colspan="2" style="border-bottom: 1px solid; border-right: 1px solid">
            <select :value="calendar.view" @change="(e: any) => calendar?.changeView(e.target.value)">
              <option value="month">Month</option>
              <option value="week">Week</option>
              <option value="day">Day</option>
            </select>
          </th>
        </tr>
      </thead>
      <tbody>
        <template v-if="calendar.view === 'month'">
          <tr>
            <th v-for="day in calendar.utils.daysofWeek('short')" :key="day"
              style="width: 120px; border-right: 1px solid; border-bottom: 1px solid">
              {{ day }}
            </th>
          </tr>
          <tr v-for="(week, i) in calendar.monthData?.weeks" :key="i">
            <td v-for="(date, j) in week" :key="j" :style="{
              color: !calendar.monthData?.isCurrentMonth(date) ? 'gray' : undefined,
              fontWeight: calendar.monthData?.isToday(date) ? 'bold' : 'normal',
              borderRight: '1px solid',
              borderBottom: '1px solid',
            }">
              {{ calendar.utils.formatDate(date, 'd') }}
            </td>
          </tr>
        </template>

        <tr v-if="calendar.view === 'week'">
          <td colspan="7" style="border-right: 1px solid">
            <table cellpadding="5" cellspacing="0" width="100%">
              <tbody>
                <tr>
                  <td></td>
                  <td v-for="(date, i) in calendar.weekData?.dates" :key="i"
                    :style="{ fontWeight: calendar.weekData?.isToday(date) ? 'bold' : 'normal' }">
                    {{ calendar.utils.formatDateTime(date, 'EEE d') }}
                  </td>
                </tr>
                <tr v-for="slot in calendar.timeSlots" :key="slot.time">
                  <td style="border-bottom: 1px solid">
                    {{ slot.label }}
                  </td>
                  <td v-for="(date, i) in calendar.weekData?.dates" :key="i" :style="{
                    fontWeight: calendar.weekData?.isToday(date) ? 'bold' : 'normal',
                    borderBottom: '1px solid',
                  }">
                    &nbsp;
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
        </tr>

        <template v-if="calendar.view === 'day'">
          <tr>
            <td colspan="7" align="center" style="border-right: 1px solid; border-bottom: 1px solid">
              {{ calendar.dayData?.dayName }}
            </td>
          </tr>
          <tr>
            <td colspan="7" style="border-right: 1px solid">
              <table width="100%" cellspacing="0" style="height: 100%">
                <tbody>
                  <tr v-for="slot in calendar.timeSlots" :key="slot.time">
                    <td width="25%" style="border-bottom: 1px solid">
                      {{ slot.label }}
                      &nbsp;
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>
          </tr>
        </template>
      </tbody>
    </table>
  </div>
</template>

// examples/React/basic/src/calendar.tsx
import React, { JSX } from "react";
import { useCalendar, type ViewType } from "@verbpatch/react-calendar";

export const CalendarDemo: React.FC = () => {
  const {
    view,
    changeView,

    monthData,
    weekData,
    dayData,
    timeSlots,

    goToPrevious,
    goToToday,
    goToNext,

    utils: { formatDate, formatDateTime, daysofWeek },
  } = useCalendar({
    defaultView: "month",
    startOfWeek: 0, // 0 = Sunday, 1 = Monday
  });

  const renderMonthView = (): JSX.Element | null => {
    if (!monthData) return null;
    return (
      <>
        <tr>
          {daysofWeek("long").map((day) => (
            <td style={{ width: "120px", borderRight: "1px solid", borderBottom: "1px solid" }} key={day}>
              {day}
            </td>
          ))}
        </tr>

        {monthData.weeks.map((week, weekIndex) => (
          <tr key={weekIndex}>
            {week.map((date, dayIndex) => {
              const isCurrentMonth = monthData!.isCurrentMonth(date);
              const isToday = monthData!.isToday(date);

              return (
                <td
                  align="center"
                  key={dayIndex}
                  style={{
                    fontWeight: isToday ? "bold" : "normal",
                    color: isCurrentMonth ? "black" : "gray",
                    borderRight: "1px solid",
                    borderBottom: "1px solid",
                  }}
                >
                  <div>{formatDate(date, "d")}</div>
                </td>
              );
            })}
          </tr>
        ))}
      </>
    );
  };

  const renderWeekView = (): JSX.Element | null => {
    if (!weekData) return null;

    return (
      <tr>
        <td colSpan={7} style={{ borderRight: "1px solid" }}>
          <table cellPadding="5" cellSpacing="0" width="100%">
            <tbody>
              <tr>
                <td></td>
                {weekData.dates.map((date, index) => (
                  <td key={index} style={{ fontWeight: weekData!.isToday(date) ? "bold" : "normal" }}>
                    {formatDateTime(date, "d MMM")}
                  </td>
                ))}
              </tr>

              {timeSlots.map((slot) => (
                <tr key={slot.label} data-key={slot.label}>
                  <td style={{ borderBottom: "1px solid" }}>
                    <div key={slot.time} data-slot={slot.time}>
                      {slot.label}
                    </div>
                  </td>
                  {weekData.dates.map((date, dateIndex) => {
                    return <td key={dateIndex} data-date={formatDate(date)} data-slot={slot.time} style={{ borderBottom: "1px solid", fontWeight: weekData!.isToday(date) ? "bold" : "normal" }}></td>;
                  })}
                </tr>
              ))}
            </tbody>
          </table>
        </td>
      </tr>
    );
  };

  const renderDayView = (): JSX.Element | null => {
    if (!dayData) return null;
    return (
      <>
        <tr>
          <td colSpan={7} style={{ borderRight: "1px solid", borderBottom: "1px solid", textAlign: "center" }}>
            {dayData.dayName}
          </td>
        </tr>

        {timeSlots.map((slot) => (
          <tr>
            <td colSpan={7} style={{ borderRight: "1px solid", borderBottom: "1px solid" }}>
              <div key={slot.time} data-time={slot.time} data-day={formatDate(dayData.date)}>
                {slot.label}
              </div>
            </td>
          </tr>
        ))}
      </>
    );
  };

  return (
    <table border={0} cellPadding={0} cellSpacing={0} width={840} style={{ height: "700px", borderLeft: "1px solid", borderTop: "1px solid" }}>
      <thead>
        <tr>
          <th colSpan={2} style={{ borderBottom: "1px solid" }}>
            <button type="button" onClick={goToPrevious}>
              ←
            </button>
            <button type="button" onClick={goToToday}>
              Today
            </button>

            <button type="button" onClick={goToNext}>
              →
            </button>
          </th>
          <th colSpan={3} style={{ borderBottom: "1px solid" }}>
            <h3>
              {view === "month" && monthData?.monthName}
              {view === "week" && weekData?.weekRange}
              {view === "day" && dayData?.dayName}
            </h3>
          </th>
          <th colSpan={2} style={{ borderBottom: "1px solid", borderRight: "1px solid" }}>
            <select
              onChange={(s) => {
                const value = (s.target as HTMLSelectElement).value as ViewType;
                changeView(value);
              }}
            >
              <option value="month">Month</option>
              <option value="week">Week</option>
              <option value="day">Day</option>
            </select>
          </th>
        </tr>
      </thead>
      <tbody>
        {view === "month" && renderMonthView()}
        {view === "week" && renderWeekView()}
        {view === "day" && renderDayView()}
      </tbody>
    </table>
  );
};
